{
 "title": "bliFood dashboard",
 "tags": [ "blifood" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{exported_job=\"blifood\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "system_cpu_usage{exported_job=\"blifood\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{exported_job=\"blifood\"})/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(jvm_memory_committed_bytes{exported_job=\"blifood\"})/1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n    +\r\n    (\r\n        (\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"500\", status=~\"2..\"}[$__rate_interval]))\r\n          -\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n        ) / 2\r\n    )\r\n )\r\n /\r\n sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"[25]..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\nsum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"5..\"}[$__rate_interval]))\r\n/\r\nsum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))*100 or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n    +\r\n    (\r\n        (\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"500\", status=~\"2..\"}[$__rate_interval]))\r\n          -\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n        ) / 2\r\n    )\r\n )\r\n /\r\n sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"[25]..\"}[$__rate_interval]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))*60",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\nsum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  { "title": "Path Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Throughput by path",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))  by (uri,method) * 60 > 0",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  },
  {
   "title": "Response time by path",
   "type": "timeseries",
   "description": "Tempo de resposta",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(method,uri) (rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\nsum by(method,uri) (rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
     "legendFormat": "{{uri}} {{method}}"
    }
   ]
  }
 ]
}