server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDb
    username: local/blifood/databaseUser
    password: local/blifood/databasePassword
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration,classpath:db/testdata

blifood:
  email:
    impl: fake
    from: bliFood <noreply@blifood.com.br>
  storage:
    type: local
    local:
      path: ./catalog
  jwt-keystore:
    jks-location: secretsManager:local/blifood/jwtKey
    password: secretsManager:local/blifood/jwtPassword
    keypair-alias: secretsManager:local/blifood/jwtAlias
