spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: blifood
  jpa:
    properties:
      hibernate:
        default_schema: blifood

logging:
  pattern:
    level: '[traceId:%X{traceId} spanId:%X{spanId}] %6level'

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  otlp:
    metrics:
      export:
        resourceAttributes:
          service.name: blifood
  metrics:
    distribution:
      slo:
        http.server.requests: 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 2500ms, 5000ms, 10000ms
      percentiles:
        http.server.requests: 0.9, 0.95, 0.99