spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDb
    username: prod/blifood/databaseUser
    password: prod/blifood/databasePassword
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: secretsmanager:prod/blifood/emailApikey
    password: secretsmanager:prod/blifood/emailPassword

blifood:
  logging:
    invalid-requests: false
  secrets-manager:
    impl: ${BLIFOOD_SECRETS_MANAGER_IMPL:aws}
  cache:
    impl: redis
    redis:
      host: localhost
      port: 6379
  email:
    impl: smtp
  storage:
    type: S3
    s3:
      access-key: secretsmanager:prod/blifood/s3AccessKey
      secret-access-key: secretsmanager:prod/blifood/s3SecretAccessKey
      bucket: blifood-prod
      region: us-east-1
      path: catalog
