spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: blifood
  jpa:
    properties:
      hibernate:
        default_schema: blifood

