server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgresDb
    username: local/blifood/databaseUser
    password: local/blifood/databasePassword
  jpa:
    show-sql: false
  flyway:
    locations: classpath:db/migration,classpath:db/testdata

blifood:
  email:
    impl: fake
    from: bliFood <noreply@blifood.com.br>
  storage:
    type: local
    local:
      path: ./catalog
  jwt-keystore:
    jks-location: secretsmanager:local/blifood/jwtKey
    password: secretsmanager:local/blifood/jwtPassword
    keypair-alias: secretsmanager:local/blifood/jwtAlias

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        resourceAttributes:
          service.name: blifood
  metrics:
    distribution:
      slo:
        http.server.requests: "5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1000ms, 2500ms, 5000ms, 10000ms"
      percentiles:
        http.server.requests: "0.5, 0.95, 0.99"