{
 "title": "bliFood dashboard",
 "tags": [ "blifood" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_usage{exported_job=\"blifood\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "system_cpu_usage{exported_job=\"blifood\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{exported_job=\"blifood\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total{exported_job=\"blifood\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{exported_job=\"blifood\"}[$__rate_interval])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{exported_job=\"blifood\"}[$__rate_interval])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n    +\r\n    (\r\n        (\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"500\", status=~\"2..\"}[$__rate_interval]))\r\n          -\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n        ) / 2\r\n    )\r\n )\r\n /\r\n sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"[25]..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\navg(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"5..\"}[$__rate_interval]))\r\n/\r\nsum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(\r\n    sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n    +\r\n    (\r\n        (\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"500\", status=~\"2..\"}[$__rate_interval]))\r\n          -\r\n          sum(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__rate_interval]))\r\n        ) / 2\r\n    )\r\n )\r\n /\r\n sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"[25]..\"}[$__rate_interval]))",
     "legendFormat": "Apdex"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))*60",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "avg(rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\navg(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
     "legendFormat": "Average Latency"
    }
   ]
  },
  {
   "title": "Business Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orders",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      {
       "expr": "round(sum by(status)(increase(blifood_order_total{exported_job=\"blifood\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Orders",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum by(status)(increase(blifood_order_total{exported_job=\"blifood\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Path Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "(\r\n    sum by(uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__range]))\r\n    +\r\n    (\r\n        (\r\n          sum by(uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"500\", status=~\"2..\"}[$__range]))\r\n          -\r\n          sum by(uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\", le=\"250\", status=~\"2..\"}[$__range]))\r\n        ) / 2\r\n    )\r\n )\r\n /\r\n sum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"[25]..\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__range])*60) "
      },
      {
       "expr": "sum by(uri,method)(rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__range]))\r\n/\r\nsum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__range]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le, uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, uri,method)(rate(http_server_requests_milliseconds_bucket{exported_job=\"blifood\"}[$__range])))",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\r\n    sum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\", status=~\"5..\"}[$__range]))\r\n    or\r\n    sum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__range])) * 0\r\n)\r\n/\r\nsum by(uri,method)(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))  by (uri,method) * 60 > 0",
       "legendFormat": "{{uri}} {{method}}"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "description": "Tempo de resposta",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by(method,uri) (rate(http_server_requests_milliseconds_sum{exported_job=\"blifood\"}[$__rate_interval]))\r\n/\r\nsum by(method,uri) (rate(http_server_requests_milliseconds_count{exported_job=\"blifood\"}[$__rate_interval]))",
       "legendFormat": "{{uri}} {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Circuit Breaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Open",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "resilience4j_circuitbreaker_state{exported_job=\"blifood\",state=~\"open|forced_open|half_open\"} > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
     "targets": [
      {
       "expr": "round(sum by(status)(increase(http_client_requests_milliseconds_count{exported_job=\"blifood\", status!~\"2..\"}[$__range])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum by(name, status)(increase(http_client_requests_milliseconds_count{exported_job=\"blifood\", status!~\"2..\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{exported_job=\"blifood\", level=\"info\"}[$__rate_interval]))",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(logback_events_total{exported_job=\"blifood\", level=\"error\"}[$__rate_interval]))",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}