receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  # Porta que recebe métricas OTLP

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"  # Porta onde o Prometheus irá buscar as métricas

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
